/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.7
 * Generated at: 2019-01-26 19:44:22 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class loign_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=ISO-8859-1\">\r\n");
      out.write("<style>\r\n");
      out.write("*, *:before, *:after {\r\n");
      out.write("  -moz-box-sizing: border-box;\r\n");
      out.write("  -webkit-box-sizing: border-box;\r\n");
      out.write("  box-sizing: border-box;\r\n");
      out.write("}\r\n");
      out.write("body {\r\n");
      out.write("  font-family: 'Nunito', sans-serif;\r\n");
      out.write("  color: #384047;\r\n");
      out.write("}\r\n");
      out.write("form {\r\n");
      out.write("  max-width: 300px;\r\n");
      out.write("  margin: 10px auto;\r\n");
      out.write("  padding: 10px 20px;\r\n");
      out.write("  background: #f4f7f8;\r\n");
      out.write("  border-radius: 8px;\r\n");
      out.write("}\r\n");
      out.write("h1 {\r\n");
      out.write("  text-align: center;\r\n");
      out.write("  padding: 0 0 20px 0;\r\n");
      out.write("}\r\n");
      out.write("input[type=\"text\"],\r\n");
      out.write("input[type=\"tel\"],\r\n");
      out.write("input[type=\"email\"],\r\n");
      out.write("input[type=\"password\"],\r\n");
      out.write("textarea,\r\n");
      out.write("select{\r\n");
      out.write("  background: rgba(255,255,255,0.1);\r\n");
      out.write("  background-color: #e8eeef;\r\n");
      out.write("  border-radius: 3px;\r\n");
      out.write("  font-size: 16px;\r\n");
      out.write("  height: auto;\r\n");
      out.write("  width: 100%;\r\n");
      out.write("  padding: 5px;\r\n");
      out.write("  margin: 0;\r\n");
      out.write("  margin-bottom: 30px;\r\n");
      out.write("  outline: 0;\r\n");
      out.write("  color: #8a97a0;\r\n");
      out.write("  box-shadow: 0 1px 0 rgba(0,0,0, .03) inset;\r\n");
      out.write("  /* - border transition around a text field on focus - */\r\n");
      out.write("  border: 2px solid;\r\n");
      out.write("  border-color: #ccc;\r\n");
      out.write("  transition: border-color, .6s;  \r\n");
      out.write("}\r\n");
      out.write("input[type=\"text\"]:focus,\r\n");
      out.write("input[type=\"tel\"]:focus,\r\n");
      out.write("input[type=\"email\"]:focus,\r\n");
      out.write("input[type=\"password\"]:focus,\r\n");
      out.write("textarea:focus,\r\n");
      out.write("select:focus {\r\n");
      out.write("  border-color: #5fcf80;  \r\n");
      out.write("}\r\n");
      out.write("label {\r\n");
      out.write("  display: block;\r\n");
      out.write("  margin-bottom: 8px; \r\n");
      out.write("}\r\n");
      out.write("input[type=\"radio\"],\r\n");
      out.write("input[type=\"checkbox\"] {\r\n");
      out.write("  margin: 0 4px 8px 0;  \r\n");
      out.write("}\r\n");
      out.write("select {\r\n");
      out.write("  height: 32px;\r\n");
      out.write("  padding: 6px;\r\n");
      out.write("}\r\n");
      out.write("label.light {\r\n");
      out.write("  display: inline;\r\n");
      out.write("  font-weight: 300;\r\n");
      out.write("}\r\n");
      out.write("button {\r\n");
      out.write("  width: 100%;\r\n");
      out.write("  background-color: #18C9D2;\r\n");
      out.write("  color: #fff;\r\n");
      out.write("  font-size: 18px;\r\n");
      out.write("  text-align: center;\r\n");
      out.write("  font-style: normal;\r\n");
      out.write("  border: 1px solid #18C9D2;\r\n");
      out.write("  border-radius: 5px;\r\n");
      out.write("  border-width: 1px 1px 3px;\r\n");
      out.write("  padding: 19px 39px 18px 39px;\r\n");
      out.write("  box-shadow: 0 -1px 0 rgba(255,255,255,0.1) inset;\r\n");
      out.write("  margin-bottom: 10px;\r\n");
      out.write("}\r\n");
      out.write("fieldset {\r\n");
      out.write("  border: none;\r\n");
      out.write("  margin-bottom: 30px;\r\n");
      out.write("}\r\n");
      out.write(".number {\r\n");
      out.write("  display: inline-block;\r\n");
      out.write("  height: 30px;\r\n");
      out.write("  width: 30px;\r\n");
      out.write("  color: #fff;\r\n");
      out.write("  font-size: .8em;\r\n");
      out.write("  text-align: center;\r\n");
      out.write("  line-height: 30px;\r\n");
      out.write("  margin-right: 4px;\r\n");
      out.write("  border-radius: 100%;\r\n");
      out.write("  background-color: #18C9D2;\r\n");
      out.write("  text-shadow: 0 1px 0 rgba(255,255,255,0.2);\r\n");
      out.write("}\r\n");
      out.write("legend {\r\n");
      out.write("  font-size: 1.4em;\r\n");
      out.write("  margin-bottom: 10px;\r\n");
      out.write("}\r\n");
      out.write("@media screen and (min-width: 480px) {\r\n");
      out.write("  form {\r\n");
      out.write("    max-width: 480px;\r\n");
      out.write("  }\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("<title>VMS Login</title>\r\n");
      out.write("<script type=\"applijegleryion/x-javascript\"> addEventListener(\"load\", function() { setTimeout(hideURLbar, 0); }, false); function hideURLbar(){ window.scrollTo(0,1); } </script>\r\n");
      out.write("<link href=\"css/bootstrap.css\" rel='stylesheet' type='text/css' />\r\n");
      out.write("<!-- Custom Theme files -->\r\n");
      out.write("<link href=\"css/style.css\" rel='stylesheet' type='text/css' />\t\r\n");
      out.write("<script src=\"js/jquery-1.11.1.min.js\"></script>\r\n");
      out.write("<!-- start menu -->\r\n");
      out.write("<link href=\"css/megamenu.css\" rel=\"stylesheet\" type=\"text/css\" media=\"all\" />\r\n");
      out.write("<script type=\"text/javascript\" src=\"js/megamenu.js\"></script>\r\n");
      out.write("<script>$(document).ready(function(){$(\".megamenu\").megamenu();});</script>\r\n");
      out.write("<script src=\"js/menu_jquery.js\"></script>\r\n");
      out.write("<script src=\"js/simpleCart.min.js\"> </script>\r\n");
      out.write("<!--web-fonts-->\r\n");
      out.write(" <link href='//fonts.googleapis.com/css?family=Open+Sans:400,300,400italic,300italic,600,700' rel='stylesheet' type='text/css'>\r\n");
      out.write(" <link href='//fonts.googleapis.com/css?family=Roboto+Slab:300,400,700' rel='stylesheet' type='text/css'>\r\n");
      out.write("<!--//web-fonts-->\r\n");
      out.write(" <script src=\"js/scripts.js\" type=\"text/javascript\"></script>\r\n");
      out.write("<script src=\"js/modernizr.custom.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"js/move-top.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"js/easing.js\"></script>\r\n");
      out.write("<!--/script-->\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("\t\t\tjQuery(document).ready(function($) {\r\n");
      out.write("\t\t\t\t$(\".scroll\").click(function(event){\t\t\r\n");
      out.write("\t\t\t\t\tevent.preventDefault();\r\n");
      out.write("\t\t\t\t\t$('html,body').animate({scrollTop:$(this.hash).offset().top},900);\r\n");
      out.write("\t\t\t\t});\r\n");
      out.write("\t\t\t});\r\n");
      out.write("</script>\r\n");
      out.write("<script id=\"jsbin-javascript\">\r\n");
      out.write("(function (global) {\r\n");
      out.write("\tif(typeof (global) === \"undefined\")\r\n");
      out.write("\t{\r\n");
      out.write("\t\tthrow new Error(\"window is undefined\");\r\n");
      out.write("\t}\r\n");
      out.write("    var _hash = \"!\";\r\n");
      out.write("    var noBackPlease = function () {\r\n");
      out.write("        global.location.href += \"#\";\r\n");
      out.write("\t\t// making sure we have the fruit available for juice....\r\n");
      out.write("\t\t// 50 milliseconds for just once do not cost much (^__^)\r\n");
      out.write("        global.setTimeout(function () {\r\n");
      out.write("            global.location.href += \"!\";\r\n");
      out.write("        }, 50);\r\n");
      out.write("    };\t\r\n");
      out.write("\t// Earlier we had setInerval here....\r\n");
      out.write("    global.onhashchange = function () {\r\n");
      out.write("        if (global.location.hash !== _hash) {\r\n");
      out.write("            global.location.hash = _hash;\r\n");
      out.write("        }\r\n");
      out.write("    };\r\n");
      out.write("    global.onload = function () {        \r\n");
      out.write("\t\tnoBackPlease();\r\n");
      out.write("\t\t// disables backspace on page except on input fields and textarea..\r\n");
      out.write("\t\tdocument.body.onkeydown = function (e) {\r\n");
      out.write("            var elm = e.target.nodeName.toLowerCase();\r\n");
      out.write("            if (e.which === 8 && (elm !== 'input' && elm  !== 'textarea')) {\r\n");
      out.write("                e.preventDefault();\r\n");
      out.write("            }\r\n");
      out.write("            // stopping event bubbling up the DOM tree..\r\n");
      out.write("            e.stopPropagation();\r\n");
      out.write("        };\t\t\r\n");
      out.write("    };\r\n");
      out.write("})(window);\r\n");
      out.write("</script>\r\n");
      out.write("<!-- the jScrollPane script -->\r\n");
      out.write("<script type=\"text/javascript\" src=\"js/jquery.jscrollpane.min.js\"></script>\r\n");
      out.write("\t\t<script type=\"text/javascript\" id=\"sourcecode\">\r\n");
      out.write("\t\t\t$(function()\r\n");
      out.write("\t\t\t{\r\n");
      out.write("\t\t\t\t$('.scroll-pane').jScrollPane();\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t</script>\r\n");
      out.write("<!-- //the jScrollPane script -->\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("<!--start-home-->\r\n");
      out.write("<!-- header_top -->\r\n");
      out.write("<div class=\"top_bg\" id=\"home\">\r\n");
      out.write("\t<div class=\"container\">\r\n");
      out.write("\t\t<div class=\"header_top\">\r\n");
      out.write("\t\t\t<div class=\"top_right\">\r\n");
      out.write("\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"signup.jsp\">Register an Account</a></li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"login.jsp\">Login Please</a></li>\t\t\t\t\r\n");
      out.write("\t\t\t\t</ul>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"clearfix\"> </div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("</div>\r\n");
      out.write("<!-- header -->\r\n");
      out.write("<div class=\"header_bg\">\r\n");
      out.write("   <div class=\"container\">\r\n");
      out.write("\t<div class=\"header\">\r\n");
      out.write("\t  <div class=\"head-t\">\r\n");
      out.write("\t\t <div class=\"logo\">\r\n");
      out.write("\t\t\t  <a href=\"index.php\"><h1>Vehicle <span>Management</span></h1> </a>\r\n");
      out.write("\t\t  </div>\r\n");
      out.write("\t\t  <div class=\"header_right\">\r\n");
      out.write("\t\t\t<div class=\"cart box_1\">\r\n");
      out.write("\t\t\t\t<a href=\"#\">\r\n");
      out.write("\t\t\t\t<div>\r\n");
      out.write("\t\t\t\t<a  href=\"#\"><img src=\"images/logo.png\" width=\"80px\" height=\"80px\" /></a></div>\r\n");
      out.write("\t\t\t\t<div class=\"clearfix\"> </div> \r\n");
      out.write("\t\t\t</div>\t\t\t\t \r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"clearfix\"></div>\t\r\n");
      out.write("\t    </div>\r\n");
      out.write("\t\t<!--start-header-menu-->\r\n");
      out.write("\t</div>\r\n");
      out.write("</div>\r\n");
      out.write("</div>\r\n");
      out.write(" <!--start-content-->\r\n");
      out.write("<!--products-->\r\n");
      out.write("\t<div class=\"products\">\r\n");
      out.write("<form action=\"/vms/Login\" method=\"post\">\r\n");
      out.write("  <div class=\"megamenu skyblue\">\r\n");
      out.write("  <center><h2>LOGIN</h2></center>\r\n");
      out.write("  </div>\r\n");
      out.write("  <br>\r\n");
      out.write("  <fieldset>\r\n");
      out.write("    <label for=\"name\"><h3>Username:</h3></label>\r\n");
      out.write("    <input type=\"text\" id=\"username\" name=\"user_name\" >\r\n");
      out.write("    <label for=\"passw\"><h3>Password:</h3></label>\r\n");
      out.write("    <input type=\"password\" id=\"passw\" name=\"user_password\" >   \r\n");
      out.write("    <button type=\"submit\"><h3>Login</h3></button>\r\n");
      out.write("</form>\r\n");
      out.write("\t</div>\r\n");
      out.write("<!-- //products -->\r\n");
      out.write("\t  <!--start-image-cursuals-->\r\n");
      out.write("                  <div class=\"scroll-slider\">\r\n");
      out.write("                  \t<div class=\"container\"> \t\t\t\t\t\t\t\t\t\t\t \r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"nbs-flexisel-container\"><div class=\"nbs-flexisel-inner\"><ul class=\"flexiselDemo3 nbs-flexisel-ul\" style=\"left: -253.6px; display: block;\">\t\t\t\t\t    \t\t\t\t\t    \t\t\t\t\t       \r\n");
      out.write("\t\t\t\t\t\t\t<li onclick=\"location.href='#';\" class=\"nbs-flexisel-item\" style=\"width: 253.6px;\"><img src=\"images/c3.png\" alt=\"\"/></li><li onclick=\"location.href='#';\" class=\"nbs-flexisel-item\" style=\"width: 253.6px;\"><img src=\"images/c4.png\" alt=\"\"/></li><li onclick=\"location.href='#';\" class=\"nbs-flexisel-item\" style=\"width: 253.6px;\"><img src=\"images/c1.png\" alt=\"\"/></li><li onclick=\"location.href='#';\" class=\"nbs-flexisel-item\" style=\"width: 253.6px;\"><img src=\"images/c2.png\" alt=\"\"/></li><li onclick=\"location.href='#';\" class=\"nbs-flexisel-item\" style=\"width: 253.6px;\"><img src=\"images/c3.png\" alt=\"\"/></li><li onclick=\"location.href='#';\" class=\"nbs-flexisel-item\" style=\"width: 253.6px;\"><img src=\"images/c4.png\" alt=\"\"/></li><li onclick=\"location.href='#';\" class=\"nbs-flexisel-item\" style=\"width: 253.6px;\"><img src=\"images/c1.png\" alt=\"\"/></li><li onclick=\"location.href='#';\" class=\"nbs-flexisel-item\" style=\"width: 253.6px;\"><img src=\"images/c2.png\" alt=\"\"/></li></ul><div class=\"nbs-flexisel-nav-left\" style=\"top: 21.5px;\"></div><div class=\"nbs-flexisel-nav-right\" style=\"top: 21.5px;\"></div></div></div> \r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"clearfix\"> </div>      \r\n");
      out.write("\t\t\t\t\t\t  <!--start-image-->\r\n");
      out.write("\t\t\t\t\t\t\t\t<script type=\"text/javascript\" src=\"js/jquery.flexisel.js\"></script>\r\n");
      out.write("\t\t\t\t\t\t\t\t<!--//end-->\r\n");
      out.write("\t\t\t\t\t\t\t\t<script type=\"text/javascript\">\r\n");
      out.write("\t\t\t\t\t\t\t\t$(window).load(function() {\r\n");
      out.write("\t\t\t\t\t\t\t\t    $(\".flexiselDemo3\").flexisel({\r\n");
      out.write("\t\t\t\t\t\t\t\t        visibleItems: 5,\r\n");
      out.write("\t\t\t\t\t\t\t\t        animationSpeed: 1000,\r\n");
      out.write("\t\t\t\t\t\t\t\t        autoPlay: true,\r\n");
      out.write("\t\t\t\t\t\t\t\t        autoPlaySpeed: 3000,            \r\n");
      out.write("\t\t\t\t\t\t\t\t        pauseOnHover: true,\r\n");
      out.write("\t\t\t\t\t\t\t\t        enableResponsiveBreakpoints: true,\r\n");
      out.write("\t\t\t\t\t\t\t\t        responsiveBreakpoints: { \r\n");
      out.write("\t\t\t\t\t\t\t\t            portrait: { \r\n");
      out.write("\t\t\t\t\t\t\t\t                changePoint:480,\r\n");
      out.write("\t\t\t\t\t\t\t\t                visibleItems: 2\r\n");
      out.write("\t\t\t\t\t\t\t\t            }, \r\n");
      out.write("\t\t\t\t\t\t\t\t            landscape: { \r\n");
      out.write("\t\t\t\t\t\t\t\t                changePoint:640,\r\n");
      out.write("\t\t\t\t\t\t\t\t                visibleItems: 3\r\n");
      out.write("\t\t\t\t\t\t\t\t            },\r\n");
      out.write("\t\t\t\t\t\t\t\t            tablet: { \r\n");
      out.write("\t\t\t\t\t\t\t\t                changePoint:768,\r\n");
      out.write("\t\t\t\t\t\t\t\t                visibleItems: 3\r\n");
      out.write("\t\t\t\t\t\t\t\t            }\r\n");
      out.write("\t\t\t\t\t\t\t\t        }\r\n");
      out.write("\t\t\t\t\t\t\t\t    });\r\n");
      out.write("\t\t\t\t\t\t\t\t});\r\n");
      out.write("\t\t\t\t\t\t\t\t</script>\r\n");
      out.write("\t\t\t\t\t\t<!---->\r\n");
      out.write("\t\t\t\t  </div>\t\t\t\t\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write(" <!--//end-bottom-->\r\n");
      out.write("\t\t<!--start-footer-->\r\n");
      out.write("\t     <div class=\"footer\">\r\n");
      out.write("\t\t   <div class=\"container\">\r\n");
      out.write("\t\t\t<div class=\"footer-top\">\r\n");
      out.write("\t\t\t\t<div class=\"col-md-2 footer-left\">\r\n");
      out.write("\t\t\t\t\t<h3>About Us</h3>\r\n");
      out.write("\t\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"contact.jsp\">Contact Us</a></li>\t\t\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"#\">.</a></li>\t\t \r\n");
      out.write("\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t<div class=\"clearfix\"> </div>\r\n");
      out.write("\t\t\t</div>\t\t\t\t\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<ul class=\"socials\">\r\n");
      out.write("\t\t\t\t    <li><a class=\"soc1\" href=\"https://en-gb.facebook.com/login/\"></a></li>\r\n");
      out.write("\t\t\t\t    <li><a class=\"soc2\" href=\"https://twitter.com/login\"></a></li>\r\n");
      out.write("\t\t\t\t</ul>\r\n");
      out.write("\t <!--/start-copyright-->\r\n");
      out.write("\t <div class=\"copy\">\r\n");
      out.write("\t\t<div class=\"container\">\r\n");
      out.write("\t\t\t<p>&copy; 2019 All Rights Reserved </p>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t <!--//end-copyright-->\r\n");
      out.write("\t<!--end-footer-->\r\n");
      out.write(" <!--//end-content-->\r\n");
      out.write("    \t<!--start-smooth-scrolling-->\r\n");
      out.write("\t\t\t\t\t\t<script type=\"text/javascript\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t$(document).ready(function() {\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t/*\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tvar defaults = {\r\n");
      out.write("\t\t\t\t\t\t\t\t  \t\t\tcontainerID: 'toTop', // fading element id\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tcontainerHoverID: 'toTopHover', // fading element hover id\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tscrollSpeed: 1200,\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\teasingType: 'linear' \r\n");
      out.write("\t\t\t\t\t\t\t\t \t\t};\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t*/\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t$().UItoTop({ easingType: 'easeOutQuart' });\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t});\r\n");
      out.write("\t\t\t\t\t\t\t\t</script>\r\n");
      out.write("\t\t<a href=\"#home\" id=\"toTop\" class=\"scroll\" style=\"display: block;\"> <span id=\"toTopHover\" style=\"opacity: 1;\"> </span></a>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
